'use server';

/**
 * @fileOverview This file defines a Genkit flow for answering customer questions about Vexa AI's services.
 *
 * The flow takes a customer's question as input and returns an answer generated by the AI.
 * - answerCustomerQuestions - A function that handles the customer question answering process.
 * - AnswerCustomerQuestionsInput - The input type for the answerCustomerQuestions function.
 * - AnswerCustomerQuestionsOutput - The return type for the answerCustomerQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerCustomerQuestionsInputSchema = z.object({
  question: z
    .string()
    .describe('The question from the customer about Vexa AI services.'),
});
export type AnswerCustomerQuestionsInput = z.infer<
  typeof AnswerCustomerQuestionsInputSchema
>;

const AnswerCustomerQuestionsOutputSchema = z.object({
  answer: z
    .string()
    .describe('The answer to the customer question about Vexa AI services.'),
});
export type AnswerCustomerQuestionsOutput = z.infer<
  typeof AnswerCustomerQuestionsOutputSchema
>;

export async function answerCustomerQuestions(
  input: AnswerCustomerQuestionsInput
): Promise<AnswerCustomerQuestionsOutput> {
  return answerCustomerQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerCustomerQuestionsPrompt',
  input: {schema: AnswerCustomerQuestionsInputSchema},
  output: {schema: AnswerCustomerQuestionsOutputSchema},
  prompt: `You are a customer service representative for Vexa AI.

  Answer the following question about Vexa AI's services:

  Question: {{{question}}}

  Be concise and professional in your response.
  Vexa AI provides Gen AI, software development and cloud services.`,
});

const answerCustomerQuestionsFlow = ai.defineFlow(
  {
    name: 'answerCustomerQuestionsFlow',
    inputSchema: AnswerCustomerQuestionsInputSchema,
    outputSchema: AnswerCustomerQuestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
